version: '3'

services:
  backend:
    build:
      context: .
    networks:
      - app
    expose:
      - "8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    exposes:
      - "80"
      - "443"
    networks:
      - app