version: '3'

networks:
  app:
    driver: bridge
 
services:
  app:
    build:
      context: .
    volumes:
      - static_volume:/code/static_root
      - media_volume:/code/.media
    command: >
      bash -c "
        python3 manage.py collectstatic --noinput &&
        gunicorn config.wsgi
      "
    networks:
      - app
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/code/.static
      - media_volume:/code/.media
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
