# Generated by Django 4.0 on 2021-12-13 08:49

from django.db import migrations, models

import blog.post.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_filename", models.CharField(max_length=80)),
                (
                    "path",
                    models.ImageField(upload_to=blog.post.models.Image._get_uuid_path),
                ),
            ],
            options={
                "db_table": "image",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=120, unique=True)),
                ("content", models.CharField(max_length=3000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "post",
            },
        ),
    ]
