# Generated by Django 4.0 on 2021-12-14 11:29

import blog.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Post Views'),
        ),
        migrations.AlterField(
            model_name='image',
            name='origin_filename',
            field=models.CharField(max_length=80, verbose_name='Original Image Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(upload_to=blog.post.models.Image._get_uuid_path, verbose_name='Image Path'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Post Created Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Post Modified Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(max_length=120, verbose_name='Post Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Post Title'),
        ),
    ]
